from fastapi import APIRouter

from . import (
    auth,
    stores,
    products,
    categories,
    members,
    coupons,
    promotions,
    inventories,
    orders,
    refunds,
    approvals,
    shifts,
    payments,
    invoices,
    sync,
    uploads,
    users,
    reports,
    analytics,
    member_analytics,
    member_broadcast,
    dashboard,
    dining_tables,
    table_sessions,
    guest_orders,
    public_orders,
    public_plans,
    public_members,
    public_member_center,
    public_marketplace,
    public_shopping,
    marketplace_admin,
    marketplace_payments,
    tenant_apply,
    tenant_settings,
    tenant_export,
    platform,
    purchasing,
    options,
    alliance,
    webhooks,
    books,
    events,
    line,
    print_jobs,
)

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(stores.router)
api_router.include_router(products.router)
api_router.include_router(options.product_options_router)
api_router.include_router(options.router)
api_router.include_router(categories.router)
api_router.include_router(members.router)
api_router.include_router(coupons.router)
api_router.include_router(promotions.router)
api_router.include_router(inventories.router)
api_router.include_router(purchasing.router)
api_router.include_router(orders.router)
api_router.include_router(refunds.router)
api_router.include_router(approvals.router)
api_router.include_router(shifts.router)
api_router.include_router(payments.router)
api_router.include_router(invoices.router)
api_router.include_router(sync.router)
api_router.include_router(uploads.router)
api_router.include_router(users.router)
api_router.include_router(reports.router)
api_router.include_router(analytics.router)
api_router.include_router(member_analytics.router)
api_router.include_router(member_broadcast.router)
api_router.include_router(dashboard.router)
api_router.include_router(dining_tables.router)
api_router.include_router(table_sessions.router)
api_router.include_router(guest_orders.router)
api_router.include_router(public_orders.router)
api_router.include_router(public_marketplace.router)
api_router.include_router(public_shopping.router)
api_router.include_router(marketplace_payments.router)
api_router.include_router(public_members.router)
api_router.include_router(public_member_center.router)
api_router.include_router(public_plans.router)
api_router.include_router(tenant_apply.router)
api_router.include_router(tenant_settings.router)
api_router.include_router(tenant_export.router)
api_router.include_router(marketplace_admin.router)
api_router.include_router(platform.router)
api_router.include_router(alliance.router)
api_router.include_router(webhooks.router)
api_router.include_router(books.router)
api_router.include_router(events.router)
api_router.include_router(line.router)
api_router.include_router(print_jobs.router)
